### ISSUE TITLE
Isn't the range of the JS divergence [0,1]? Why are there values greater than 1 in Figure 2?

### ISSUE THREAD

**Issue by Jeryi-Sun** [voidism/DoLa#10]
![image](https://github.com/voidism/DoLa/assets/51322811/22fcb0ad-7b2e-4673-88f2-f27558cf12ff)

**Comment by voidism** [comment]
Hi,

The numbers in Figure 2 are actually scaled by $10^5$ so they are all between [0, 1]. We forgot to include this detail in the first version of our arxiv paper. But we have included this in the openreview version (See the caption of Figure 2): https://openreview.net/pdf?id=Th6NyL07na
