### ISSUE TITLE
What tool do you use to get the token prediction of each layer of large language models for Figure 2?

### ISSUE THREAD

**Issue by frankdarkluo** [voidism/DoLa#12]

**Comment by voidism** [comment]
Hi @frankdarkluo 

I simply use matplotlib to make a table for figure 2!

**Comment by frankdarkluo** [comment]
Thanks for the reply! But I am not asking about the drawing. I am curious how do you get the prediction from the middle (not output) layers? Thanks.

**Comment by voidism** [comment]
Just insert some code to the transformers package (`modeling_llama.py` and `generation/utils.py`) and get the predictions along the decoding steps. It makes the code ugly but it works. I didn't use any tools for that.
